#!/usr/bin/env python3

import parsy as P
from lattec.parser import statements
from lattec import ast
# import argparse


# argp = argparse.ArgumentParser()
# argp.add_argument("input", help="compiler input file")
# argp.add_argument("-o", metavar="output_file", help="compiler output file", default=None)

# args = argp.parse_args()

# ast.pprint(expressions.expression.parse("2 + 3*4"))
try:
    ast.pprint(statements.statement.parse(
r"""{
  int r;
  int n;
  r = 1;
  n = a;
  while (n > 0)
  {
    r = r * n;
    n = n - 1;
  }
  return r;
}
"""
))
except P.ParseError as e:
    print(e)
