#!/usr/bin/env python3

from lattec import compiler, config
import argparse


argp = argparse.ArgumentParser()
argp.add_argument("input", help="compiler input file")
argp.add_argument("-o", metavar="output_file", help="compiler output file", default=None)
argp.add_argument(
    "--silent", dest="silent", help="silences errors", action='store_true', default=False)
argp.add_argument(
    "--mrjp", dest="mrjp", help="turns on special mrjp testing mode", action='store_true',
    default=False
)

args = argp.parse_args()
config.cfg["silent"] = args.silent
config.cfg["mrjp_testing"] = args.mrjp
config.cfg["input"] = args.input
config.cfg["output"] = args.o

compiler.compile()
